services:
  nginx:
    image: nginx:1.27-alpine
    container_name: lab2_nginx
    ports:
      - "8080:80"
    volumes:
      - ./www:/var/www/html
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - php

  php:
    image: php:8.2-fpm
    container_name: lab2_php
    volumes:
      - ./www:/var/www/html
      - ./vendor:/var/www/vendor
      - ./composer.json:/var/www/composer.json